#!/bin/bash

xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

if [ -f /boot/splash.png ]; then
	hsetroot -fill /boot/splash.png &
fi
unclutter &
/home/screen/piscreen/start-browser.sh &
