#!/bin/bash

xset s off         # don't activate screensaver
xset -dpms         # disable DPMS (Energy Star) features.
xset s noblank     # don't blank the video device

hsetroot -fill /boot/splash.png &
unclutter &
~/piscreen/start-browser.sh &
